-- Script generated by Redgate Compare v1.48.1.2539
SET check_function_bodies = false;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Dropping public.inventory_in_stock(integer)...';END$$;
DROP FUNCTION public.inventory_in_stock(integer);


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Dropping public.inventory_held_by_customer(integer)...';END$$;
DROP FUNCTION public.inventory_held_by_customer(integer);


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Dropping public.get_customer_balance(integer, timestamp with time zone)...';END$$;
DROP FUNCTION public.get_customer_balance(integer, timestamp with time zone);


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Dropping public.film_not_in_stock(integer, integer)...';END$$;
DROP FUNCTION public.film_not_in_stock(integer, integer);


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Dropping public.film_in_stock(integer, integer)...';END$$;
DROP FUNCTION public.film_in_stock(integer, integer);


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.inventory_in_stock(integer)...';END$$;
CREATE FUNCTION bluebox.inventory_in_stock(IN p_inventory_id integer)
RETURNS boolean
LANGUAGE plpgsql
AS $_$
DECLARE
    v_out INTEGER;
BEGIN
    -- An item is NOT in stock if there's an open rental (upper bound is NULL)
    -- or if the current time falls within an active rental period
    SELECT COUNT(rental_id) INTO v_out
    FROM bluebox.rental
    WHERE inventory_id = p_inventory_id
      AND (upper(rental_period) IS NULL OR rental_period @> now());

    RETURN v_out = 0;
END $_$;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.get_customer_balance(integer, timestamp with time zone)...';END$$;
CREATE FUNCTION bluebox.get_customer_balance(IN p_customer_id integer, IN p_effective_date timestamp with time zone)
RETURNS numeric
LANGUAGE plpgsql
AS $_$
DECLARE
    v_rental_fees NUMERIC(10,2);  -- total amount owed from rentals
    v_payments NUMERIC(10,2);     -- total payments made
BEGIN
    -- Sum of rental fees (from payment records for rentals starting before effective date)
    SELECT COALESCE(SUM(p.amount), 0) INTO v_rental_fees
    FROM bluebox.rental r
    JOIN bluebox.payment p ON r.rental_id = p.rental_id
    WHERE r.customer_id = p_customer_id
      AND lower(r.rental_period) <= p_effective_date;

    -- Sum of payments made before effective date
    SELECT COALESCE(SUM(amount), 0) INTO v_payments
    FROM bluebox.payment
    WHERE customer_id = p_customer_id
      AND payment_date <= p_effective_date;

    -- In your current model, payment is created when rental ends,
    -- so balance should typically be 0. But this preserves the 
    -- "what did they owe as of date X" logic.
    RETURN v_rental_fees - v_payments;
END $_$;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.film_not_in_stock(integer, integer)...';END$$;
CREATE FUNCTION bluebox.film_not_in_stock(IN p_film_id integer, IN p_store_id integer, OUT p_film_count integer)
RETURNS SETOF integer
LANGUAGE sql
AS $_$
    SELECT inventory_id
    FROM bluebox.inventory
    WHERE film_id = p_film_id
      AND store_id = p_store_id
      AND NOT inventory_in_stock(inventory_id);
$_$;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.inventory_held_by_customer(integer)...';END$$;
CREATE FUNCTION bluebox.inventory_held_by_customer(IN p_inventory_id integer)
RETURNS integer
LANGUAGE plpgsql
AS $_$
DECLARE
    v_customer_id INTEGER;
BEGIN
    SELECT customer_id INTO v_customer_id
    FROM bluebox.rental
    WHERE inventory_id = p_inventory_id
      AND (upper(rental_period) IS NULL OR rental_period @> now());

    RETURN v_customer_id;
END $_$;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.film_in_stock(integer, integer)...';END$$;
CREATE FUNCTION bluebox.film_in_stock(IN p_film_id integer, IN p_store_id integer, OUT p_film_count integer)
RETURNS SETOF integer
LANGUAGE sql
AS $_$
    SELECT inventory_id
    FROM bluebox.inventory
    WHERE film_id = p_film_id
      AND store_id = p_store_id
      AND inventory_in_stock(inventory_id);
$_$;

SET check_function_bodies = true;
