-- Script generated by Redgate Compare v1.48.1.2539
SET check_function_bodies = false;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.inventory_status...';END$$;
CREATE TABLE bluebox.inventory_status (
    status_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    status_code text NOT NULL,
    description text,
    display_order integer
);
ALTER TABLE bluebox.inventory_status ADD CONSTRAINT inventory_status_pkey PRIMARY KEY (status_id);
INSERT INTO bluebox.inventory_status(status_id, status_code, description, display_order) OVERRIDING SYSTEM VALUE VALUES
(1, 'in_circulation', 'Available for rental', 1),
(2, 'lost', 'Never returned, customer charged replacement cost', 2),
(3, 'damaged', 'Returned damaged, removed from circulation', 3),
(4, 'retired', 'Intentionally removed from inventory', 4)
ON CONFLICT (status_id) DO UPDATE SET status_code = EXCLUDED.status_code, description = EXCLUDED.description, display_order = EXCLUDED.display_order;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.protect_circulation_start()...';END$$;
CREATE FUNCTION bluebox.protect_circulation_start()
RETURNS trigger
LANGUAGE plpgsql
AS $_$
BEGIN
    IF OLD.circulation_start IS DISTINCT FROM NEW.circulation_start THEN
        RAISE WARNING 'circulation_start is immutable and cannot be changed (inventory_id: %). Keeping original value: %', 
            OLD.inventory_id, OLD.circulation_start;
        NEW.circulation_start := OLD.circulation_start;
    END IF;
    RETURN NEW;
END;
$_$;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.inventory_status_status_code_key...';END$$;
ALTER TABLE bluebox.inventory_status ADD CONSTRAINT inventory_status_status_code_key UNIQUE (status_code);


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.inventory.inventory_protect_circulation_start...';END$$;
CREATE TRIGGER inventory_protect_circulation_start
BEFORE UPDATE
ON bluebox.inventory
FOR EACH ROW
EXECUTE PROCEDURE bluebox.protect_circulation_start();


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.inventory.status_id...';END$$;
ALTER TABLE bluebox.inventory ADD COLUMN status_id integer NOT NULL DEFAULT 1;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.inventory.inventory_status_id_fkey...';END$$;
ALTER TABLE bluebox.inventory ADD CONSTRAINT inventory_status_id_fkey FOREIGN KEY (status_id) REFERENCES bluebox.inventory_status (status_id);


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.inventory.circulation_start...';END$$;
ALTER TABLE bluebox.inventory ADD COLUMN circulation_start timestamp with time zone NOT NULL DEFAULT now();

SET check_function_bodies = true;
