-- Script generated by Redgate Compare v1.48.1.2539
SET check_function_bodies = false;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Altering bluebox.insert_payments(date)...';END$$;
CREATE OR REPLACE PROCEDURE bluebox.insert_payments(IN rd date)
LANGUAGE plpgsql
AS $_$
BEGIN 
    WITH payment_info AS (
        SELECT 
            r.rental_id, 
            rental_period, 
            GREATEST(CEILING(EXTRACT(epoch FROM (upper(rental_period)-lower(rental_period)))/3600/24), 1) AS rental_days,
            inventory_id, 
            r.customer_id, 
            upper(rental_period) AS payment_date,
            i.film_id
        FROM bluebox.rental r
        INNER JOIN bluebox.inventory i USING(inventory_id)
        LEFT JOIN bluebox.payment p ON r.rental_id = p.rental_id
        WHERE upper(rental_period) IS NOT NULL
          AND lower(rental_period) >= rd - '1 days'::INTERVAL
          AND lower(rental_period) <= rd + '1 days'::INTERVAL
          AND p.rental_id IS NULL 
    )
    INSERT INTO bluebox.payment (customer_id, rental_id, amount, payment_date)
    SELECT 
        customer_id, 
        rental_id, 
        rental_days * bluebox.get_daily_rental_rate(film_id) AS amount, 
        payment_date
    FROM payment_info;
END;
$_$;

SET check_function_bodies = true;
