-- Script generated by Redgate Compare v1.51.0.2868
SET check_function_bodies = false;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.process_lost_rentals(interval, boolean)...';END$$;
COMMENT ON PROCEDURE bluebox.process_lost_rentals(interval, boolean) IS 'Mark very old open rentals as lost and charge replacement cost.

This procedure:
1. Finds open rentals older than p_lost_after
2. Closes the rental (sets end time to now)
3. Marks the inventory as "lost" (status_id = 2)
4. Charges the customer the film replacement cost

Parameters:
  p_lost_after   - How long before an open rental is considered lost (default: 30 days)
  p_print_debug  - Print debug messages (default: false)

Typical usage with pg_cron:
  -- Run daily at 3am to process lost rentals
  SELECT cron.schedule(''process-lost-rentals'', ''0 3 * * *'', 
      $CALL bluebox.process_lost_rentals()$);

Examples:
  -- Default: mark rentals open > 30 days as lost
  CALL bluebox.process_lost_rentals();
  
  -- More aggressive: mark rentals open > 14 days as lost
  CALL bluebox.process_lost_rentals(
      p_lost_after := interval ''14 days'',
      p_print_debug := true
  );
';


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Altering bluebox.generate_rental_history(date, date, numeric, numeric, numeric, integer, boolean)...';END$$;
CREATE OR REPLACE PROCEDURE bluebox.generate_rental_history(IN p_start_date date, IN p_end_date date DEFAULT (CURRENT_DATE - 1), IN p_min_cust_pct numeric DEFAULT 0.8, IN p_max_cust_pct numeric DEFAULT 2.5, IN p_holiday_multiplier numeric DEFAULT 2.5, IN p_store_distance integer DEFAULT 25000, IN p_print_debug boolean DEFAULT false)
LANGUAGE plpgsql
AS $_$
DECLARE
    v_current_date      date;
    v_day_start         timestamptz;
    v_day_end           timestamptz;
    v_cust_percent      numeric;
    v_is_holiday        boolean;
    v_store_id          int;
    v_local_count       int;
    v_target            int;
    v_global_target     int;
    v_active_customers  int;
    v_total_pool_size   bigint;
    v_rentals_created   int;
    v_day_rentals       int;
    v_total_rentals     int := 0;
    v_days_processed    int := 0;
    v_start_time        timestamptz;
    v_step_time         timestamptz;
BEGIN
    IF p_start_date > p_end_date THEN
        RAISE EXCEPTION 'p_end_date must be on or after p_start_date';
    END IF;
    IF p_end_date - p_start_date > 366 THEN
        RAISE EXCEPTION 'Maximum range is 366 days. Requested: % days', p_end_date - p_start_date;
    END IF;

    v_start_time := clock_timestamp();

    IF p_print_debug THEN
        RAISE NOTICE '=== Starting rental history generation ===';
        RAISE NOTICE 'Building store-customer pool (store_distance = %m)...', p_store_distance;
    END IF;

    -- ----------------------------------------------------------------
    -- Pre-compute store-customer proximity (static for the whole run).
    -- The ST_DWithin geo-join is expensive (~9s) but runs once per call
    -- regardless of how many days are generated.
    -- ----------------------------------------------------------------
    DROP TABLE IF EXISTS t_store_pool;
    CREATE TEMP TABLE t_store_pool AS
        SELECT s.store_id, c.customer_id
        FROM bluebox.store s
        JOIN bluebox.customer c ON ST_DWithin(s.geog, c.geog, p_store_distance)
        WHERE c.activebool = TRUE;

    CREATE INDEX ON t_store_pool (store_id);
    CREATE INDEX ON t_store_pool (customer_id);

    DROP TABLE IF EXISTS t_store_counts;
    CREATE TEMP TABLE t_store_counts AS
        SELECT store_id, count(*)::int AS local_count
        FROM t_store_pool
        GROUP BY store_id;

    -- Total pool pairs (sum of local_counts, NOT unique customers).
    -- Used to weight each store's share of the global daily target.
    SELECT sum(local_count) INTO v_total_pool_size FROM t_store_counts;

    SELECT count(*) INTO v_active_customers
    FROM bluebox.customer WHERE activebool = TRUE;

    IF p_print_debug THEN
        RAISE NOTICE 'Pool ready: % stores, % unique customers, % pool pairs, % seconds',
            (SELECT count(*) FROM t_store_counts),
            v_active_customers,
            v_total_pool_size,
            round(EXTRACT(EPOCH FROM clock_timestamp() - v_start_time)::numeric, 2);
        RAISE NOTICE 'Date range: % to % (% days)',
            p_start_date, p_end_date, p_end_date - p_start_date + 1;
    END IF;

    -- ----------------------------------------------------------------
    -- Temp table: tracks rented inventory and customers for the current
    -- day. Seeded once per day from bluebox.rental, then updated after
    -- each store's inserts so later stores see correct exclusions
    -- without re-scanning the main rental table per store.
    -- ----------------------------------------------------------------
    DROP TABLE IF EXISTS t_day_outstanding;
    CREATE TEMP TABLE t_day_outstanding (
        inventory_id int NOT NULL,
        customer_id  int NOT NULL
    );
    CREATE INDEX ON t_day_outstanding (customer_id);
    CREATE INDEX ON t_day_outstanding (inventory_id);

    -- ----------------------------------------------------------------
    -- Main loop: one day at a time
    -- ----------------------------------------------------------------
    v_current_date := p_start_date;

    WHILE v_current_date <= p_end_date LOOP
        v_day_start   := v_current_date::timestamptz;
        v_day_end     := (v_current_date + 1)::timestamptz;
        v_day_rentals := 0;
        v_step_time   := clock_timestamp();

        -- Seed outstanding for this day from committed rental data
        TRUNCATE t_day_outstanding;
        INSERT INTO t_day_outstanding (inventory_id, customer_id)
            SELECT inventory_id, customer_id
            FROM bluebox.rental
            WHERE rental_period && tstzrange(v_day_start, v_day_end);

        v_is_holiday := EXISTS (
            SELECT 1 FROM bluebox.holiday WHERE holiday_date = v_current_date
        );

        IF v_is_holiday THEN
            v_cust_percent := bluebox.random_between(
                p_min_cust_pct * p_holiday_multiplier,
                p_max_cust_pct * p_holiday_multiplier, 3);
        ELSE
            v_cust_percent := bluebox.random_between(p_min_cust_pct, p_max_cust_pct, 3);
        END IF;

        -- Global target: how many unique customers rent today
        v_global_target := GREATEST(1, (v_active_customers * v_cust_percent / 100)::int);

        -- --------------------------------------------------------------
        -- Inner loop: one store at a time.
        -- Each store gets a proportional share of the global target
        -- based on its local pool size relative to the total pool size.
        -- Store catchment areas overlap heavily (avg ~21 stores per
        -- customer in NYC), so naive per-store targeting would massively
        -- over-count. Proportional weighting ensures sum(store_targets)
        -- approximates the global target regardless of overlap.
        -- Stores whose proportional share rounds to 0 are skipped.
        -- --------------------------------------------------------------
        FOR v_store_id, v_local_count IN
            SELECT store_id, local_count FROM t_store_counts ORDER BY store_id
        LOOP
            v_target := round(v_global_target::numeric * v_local_count / v_total_pool_size)::int;

            CONTINUE WHEN v_target = 0;

            WITH store_customers AS MATERIALIZED (
                SELECT customer_id,
                       row_number() OVER () AS cust_rn
                FROM (
                    SELECT sp.customer_id
                    FROM t_store_pool sp
                    WHERE sp.store_id = v_store_id
                      AND sp.customer_id NOT IN (SELECT customer_id FROM t_day_outstanding)
                    ORDER BY random()
                    LIMIT v_target
                ) sub
            ),
            store_inventory AS MATERIALIZED (
                SELECT inventory_id,
                       row_number() OVER () AS inv_rn
                FROM (
                    SELECT i.inventory_id
                    FROM bluebox.inventory i
                    INNER JOIN bluebox.film f USING (film_id)
                    WHERE i.store_id = v_store_id
                      AND i.status_id = 1
                      AND i.inventory_id NOT IN (SELECT inventory_id FROM t_day_outstanding)
                      AND f.release_date <= v_current_date
                    ORDER BY random()
                    LIMIT v_target
                ) sub
            ),
            matched AS MATERIALIZED (
                SELECT sc.customer_id,
                       si.inventory_id,
                       v_day_start + (random() * 86400) * interval '1 second' AS rental_start_time,
                       COALESCE(rs.store_id, v_store_id) AS return_store_id
                FROM store_customers sc
                JOIN store_inventory si ON si.inv_rn = sc.cust_rn
                LEFT JOIN LATERAL (
                    SELECT sp.store_id
                    FROM t_store_pool sp
                    WHERE sp.customer_id = sc.customer_id
                    ORDER BY random()
                    LIMIT 1
                ) rs ON true
            ),
            created AS (
                INSERT INTO bluebox.rental (rental_period, inventory_id, customer_id, store_id)
                SELECT tstzrange(
                           rental_start_time,
                           rental_start_time + ((random() * 62 + 10) * interval '1 hour')
                       ),
                       inventory_id, customer_id, v_store_id
                FROM matched
                RETURNING inventory_id, customer_id
            ),
            -- Move inventory to the return store. The return store is chosen randomly
            -- from all nearby stores (including the rental store itself), so P(same store)
            -- = 1/N where N = number of stores near the customer. Customers near few stores
            -- will frequently return to the same location; dense urban customers will spread
            -- inventory across stores more often.
            inventory_updates AS (
                UPDATE bluebox.inventory i
                SET store_id = m.return_store_id,
                    last_update = v_day_start
                FROM matched m
                WHERE i.inventory_id = m.inventory_id
                  AND m.return_store_id != v_store_id
                RETURNING i.inventory_id
            ),
            -- Keep t_day_outstanding current so later stores in the
            -- same day exclude customers and inventory already rented
            track_outstanding AS (
                INSERT INTO t_day_outstanding (inventory_id, customer_id)
                SELECT inventory_id, customer_id FROM created
            )
            SELECT count(*) INTO v_rentals_created FROM created;

            v_day_rentals := v_day_rentals + v_rentals_created;
        END LOOP; -- store loop

        IF v_day_rentals > 0 THEN
            CALL bluebox.insert_payments(v_current_date);
        END IF;

        v_total_rentals  := v_total_rentals + v_day_rentals;
        v_days_processed := v_days_processed + 1;

        IF p_print_debug THEN
            RAISE NOTICE '% | % rentals (target %) | cust%%: % | holiday: % | % sec',
                v_current_date,
                v_day_rentals,
                v_global_target,
                round(v_cust_percent, 2),
                v_is_holiday,
                round(EXTRACT(EPOCH FROM clock_timestamp() - v_step_time)::numeric, 2);
        END IF;

        COMMIT;
        v_current_date := v_current_date + 1;
    END LOOP;

    DROP TABLE IF EXISTS t_store_pool;
    DROP TABLE IF EXISTS t_store_counts;
    DROP TABLE IF EXISTS t_day_outstanding;

    IF p_print_debug THEN
        RAISE NOTICE '=== Rental history generation complete ===';
        RAISE NOTICE 'Days processed: %, Total rentals: %, Time: % seconds',
            v_days_processed,
            v_total_rentals,
            round(EXTRACT(EPOCH FROM clock_timestamp() - v_start_time)::numeric, 2);
    END IF;
END;
$_$;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.complete_rentals(interval, numeric, numeric, integer, interval, interval, boolean)...';END$$;
COMMENT ON PROCEDURE bluebox.complete_rentals(interval, numeric, numeric, integer, interval, interval, boolean) IS 'Complete (close out) open rentals, simulating customer returns.

This procedure:
1. Finds open rentals older than p_min_rental_age
2. Skips p_skip_pct of them (these will eventually become "lost")
3. Completes p_completion_pct of them
4. Sets the rental end time (between p_min_duration and p_max_duration from start)
5. Moves inventory to a random nearby store (simulating return location)
6. Creates payment records

Parameters:
  p_min_rental_age  - Minimum time since rental start before eligible (default: 16 hours)
  p_completion_pct  - Percentage of eligible rentals to complete (default: 15%)
  p_skip_pct        - Percentage of eligible rentals to skip/ignore (default: 0.1%)
                      These accumulate and are eventually marked lost by process_lost_rentals()
  p_store_distance  - Max distance (meters) for return store (default: 25000)
  p_min_duration    - Minimum rental duration (default: 16 hours)
  p_max_duration    - Maximum rental duration (default: 96 hours)
  p_print_debug     - Print debug messages (default: false)

Typical usage with pg_cron:
  -- Complete ~15% of eligible rentals every 15 minutes
  SELECT cron.schedule(''complete-rentals'', ''*/15 * * * *'', 
      $CALL bluebox.complete_rentals()$);

Examples:
  -- Default: complete 15% of rentals older than 16 hours, skip 0.1%
  CALL bluebox.complete_rentals();
  
  -- More aggressive: complete 25% of rentals older than 12 hours
  CALL bluebox.complete_rentals(
      p_min_rental_age := interval ''12 hours'',
      p_completion_pct := 25.0,
      p_print_debug := true
  );
  
  -- Clear backlog: complete all eligible rentals (skip none)
  CALL bluebox.complete_rentals(p_completion_pct := 100.0, p_skip_pct := 0);
';

SET check_function_bodies = true;
