SET check_function_bodies = false;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Altering bluebox.staff.staff_id...';END$$;
ALTER TABLE bluebox.staff ALTER COLUMN staff_id DROP DEFAULT, ALTER COLUMN staff_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('bluebox.staff', 'staff_id'), COALESCE(MAX(staff_id), 1)) FROM bluebox.staff;

DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Dropping bluebox.staff_staff_id_seq...';END$$;
DROP SEQUENCE bluebox.staff_staff_id_seq;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Altering bluebox.language.language_id...';END$$;
ALTER TABLE bluebox.language ALTER COLUMN language_id DROP DEFAULT, ALTER COLUMN language_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('bluebox.language', 'language_id'), COALESCE(MAX(language_id), 1)) FROM bluebox.language;

DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Dropping bluebox.language_language_id_seq...';END$$;
DROP SEQUENCE bluebox.language_language_id_seq;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Altering bluebox.payment.payment_id...';END$$;
ALTER TABLE bluebox.payment ALTER COLUMN payment_id DROP DEFAULT, ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('bluebox.payment', 'payment_id'), COALESCE(MAX(payment_id), 1)) FROM bluebox.payment;

DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Dropping bluebox.payment_payment_id_seq...';END$$;
DROP SEQUENCE bluebox.payment_payment_id_seq;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Altering bluebox.inventory.inventory_id...';END$$;
ALTER TABLE bluebox.inventory ALTER COLUMN inventory_id DROP DEFAULT, ALTER COLUMN inventory_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('bluebox.inventory', 'inventory_id'), COALESCE(MAX(inventory_id), 1)) FROM bluebox.inventory;

DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Dropping bluebox.inventory_inventory_id_seq...';END$$;
DROP SEQUENCE bluebox.inventory_inventory_id_seq;


SET check_function_bodies = true;