-- Script generated by Redgate Compare v1.52.0.3327
SET check_function_bodies = false;

DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.v_customer_rentals...';END$$;
CREATE VIEW bluebox.v_customer_rentals (customer_id, full_name, email, home_store_id, activebool, rental_id, rental_date, return_date, rental_store_id, film_title, rating, amount, payment_date) AS SELECT c.customer_id,
    c.full_name,
    c.email,
    c.store_id AS home_store_id,
    c.activebool,
    r.rental_id,
    lower(r.rental_period) AS rental_date,
    upper(r.rental_period) AS return_date,
    r.store_id AS rental_store_id,
    f.title AS film_title,
    f.rating,
    p.amount,
    p.payment_date
   FROM ((((bluebox.customer c
     JOIN bluebox.rental r ON ((r.customer_id = c.customer_id)))
     JOIN bluebox.inventory i ON ((i.inventory_id = r.inventory_id)))
     JOIN bluebox.film f ON ((f.film_id = i.film_id)))
     LEFT JOIN bluebox.payment p ON ((p.rental_id = r.rental_id)));


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.v_film_catalog...';END$$;
CREATE VIEW bluebox.v_film_catalog (film_id, title, overview, release_date, rating, popularity, vote_average, vote_count, runtime, budget, revenue, original_language, genres, cast_count, crew_count) AS SELECT f.film_id,
    f.title,
    f.overview,
    f.release_date,
    f.rating,
    f.popularity,
    f.vote_average,
    f.vote_count,
    f.runtime,
    f.budget,
    f.revenue,
    f.original_language,
    string_agg(DISTINCT fg.name, ', '::text ORDER BY fg.name) AS genres,
    ( SELECT count(*) AS count
           FROM bluebox.film_cast fc
          WHERE (fc.film_id = f.film_id)) AS cast_count,
    ( SELECT count(*) AS count
           FROM bluebox.film_crew fw
          WHERE (fw.film_id = f.film_id)) AS crew_count
   FROM (bluebox.film f
     LEFT JOIN bluebox.film_genre fg ON ((fg.genre_id = ANY (f.genre_ids))))
  GROUP BY f.film_id;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.v_revenue_summary...';END$$;
CREATE VIEW bluebox.v_revenue_summary (store_id, street_name, zip_code, revenue_month, payment_count, total_revenue, avg_payment, unique_customers) AS SELECT s.store_id,
    s.street_name,
    s.zip_code,
    date_trunc('month'::text, p.payment_date) AS revenue_month,
    count(*) AS payment_count,
    sum(p.amount) AS total_revenue,
    avg(p.amount) AS avg_payment,
    count(DISTINCT p.customer_id) AS unique_customers
   FROM ((bluebox.payment p
     JOIN bluebox.rental r ON ((r.rental_id = p.rental_id)))
     JOIN bluebox.store s ON ((s.store_id = r.store_id)))
  GROUP BY s.store_id, s.street_name, s.zip_code, (date_trunc('month'::text, p.payment_date));


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.v_overdue_rentals...';END$$;
CREATE VIEW bluebox.v_overdue_rentals (rental_id, rental_date, days_outstanding, customer_id, full_name, email, phone, film_title, film_id, inventory_id, store_id, store_address, store_zip) AS SELECT r.rental_id,
    lower(r.rental_period) AS rental_date,
    (now() - lower(r.rental_period)) AS days_outstanding,
    c.customer_id,
    c.full_name,
    c.email,
    c.phone,
    f.title AS film_title,
    f.film_id,
    i.inventory_id,
    s.store_id,
    s.street_name AS store_address,
    s.zip_code AS store_zip
   FROM ((((bluebox.rental r
     JOIN bluebox.customer c ON ((c.customer_id = r.customer_id)))
     JOIN bluebox.inventory i ON ((i.inventory_id = r.inventory_id)))
     JOIN bluebox.film f ON ((f.film_id = i.film_id)))
     JOIN bluebox.store s ON ((s.store_id = r.store_id)))
  WHERE ((upper(r.rental_period) IS NULL) AND (lower(r.rental_period) < (now() - '5 days'::interval)));


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating bluebox.v_store_inventory_summary...';END$$;
CREATE VIEW bluebox.v_store_inventory_summary (store_id, street_name, zip_code, status_code, status_description, disc_count, unique_films) AS SELECT s.store_id,
    s.street_name,
    s.zip_code,
    ist.status_code,
    ist.description AS status_description,
    count(*) AS disc_count,
    count(DISTINCT i.film_id) AS unique_films
   FROM ((bluebox.inventory i
     JOIN bluebox.store s ON ((s.store_id = i.store_id)))
     JOIN bluebox.inventory_status ist ON ((ist.status_id = i.status_id)))
  GROUP BY s.store_id, s.street_name, s.zip_code, ist.status_code, ist.description;

SET check_function_bodies = true;
